"""empty message

Revision ID: 66da4f12e9f5
Revises: 3aa55e6facc4
Create Date: 2025-10-12 11:52:57.026550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66da4f12e9f5'
down_revision: Union[str, Sequence[str], None] = '3aa55e6facc4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('orders_address_id_fkey'), 'orders', type_='foreignkey')
    op.create_foreign_key(None, 'orders', 'addresses', ['address_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.create_foreign_key(op.f('orders_address_id_fkey'), 'orders', 'orders', ['address_id'], ['id'])
    # ### end Alembic commands ###
