"""empty message

Revision ID: e0bb69d72391
Revises: 66da4f12e9f5
Create Date: 2025-10-12 11:53:22.816237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0bb69d72391'
down_revision: Union[str, Sequence[str], None] = '66da4f12e9f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('product_id', sa.UUID(), nullable=False))
    op.drop_constraint(op.f('orders_prdocut_id_fkey'), 'orders', type_='foreignkey')
    op.create_foreign_key(None, 'orders', 'products', ['product_id'], ['id'])
    op.drop_column('orders', 'prdocut_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('prdocut_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.create_foreign_key(op.f('orders_prdocut_id_fkey'), 'orders', 'products', ['prdocut_id'], ['id'])
    op.drop_column('orders', 'product_id')
    # ### end Alembic commands ###
